<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>TabibAI</AssemblyName>
    <RootNamespace>TabibAI</RootNamespace>
    <Version>1.1.0</Version>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="fo-dicom" Version="5.2.6" />
    <PackageReference Include="fo-dicom.Imaging.Desktop" Version="5.2.6" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="installer/**;dist/**;distribution/**;linux/**" />
    <EmbeddedResource Remove="installer/**;dist/**;distribution/**;linux/**" />
    <None Remove="installer/**;dist/**;distribution/**;linux/**" />
  </ItemGroup>
</Project>
